### ISSUE TITLE
Markers on JBrowse

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#12]
We had a vague request from HaiYing today (summarized):
> When I BLAST something and then click on the hit (takes her to JBrowse) it would be nice to see all the wild information, as well as, Medicago, Soybean, etc.

Originally it seems like she wanted separate wild JBrowse instances that she could jump out to but the current state of these genomes doesn't fit well with that (no chromosomes yet ;-p). After more discussion it seemed like she wanted wild gene models on culinaris JBrowse but again such a thing doesn't exist.

What we have come up with to give her "wild information" on the culinaris JBrowse is to put the Exome Capture SNPs up on KnowPulse with one track per Lentil species.

**Comment by laceysanderson** [comment]
JBrowse will handle the VCF file directly: http://gmod.org/wiki/JBrowse_Configuration_Guide#Variant_Tracks_.28VCF.29
On Isilon is Larissa's directory: /projects/exploration/2017-04-10-exomecap-variants.vcf 

But it requires a compressed and indexed file:
```
   bgzip my.vcf
   tabix -p vcf my.vcf.gz
```
We will need to use VCF tools to separate our the file into each species. This would be trivial if we had a list of which species each germplasm was ;-).

This has already been done in our Medicago JBrowse. This is what goes in the trackList.json:
```js
      {
         "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
         "urlTemplate" : "raw/Mt-hapmap_filtered-set-2014Apr12.vcf.gz",
         "type" : "HTMLVariants",
         "label" : "Medicago HAPMAP Variants",
         "category" : "JCVI Reference",
         "chunkSizeLimit" : "2,000,000",
         "key" : "Medicago HAPMAP Variants"
      }
```

# TODO
- [ ] Ask Ezgy? for a list of which germplasm are wild
- [ ] Separate above VCF by Species
- [ ] BGZip & TABIX each file
- [ ] Add Track stanza to culinaris JBrowse tracklist using the Medicago Hapmap track above as an example.

**Comment by laceysanderson** [comment]
@Jiu9Shen We should really put up all RIL files available via VCF filter as well.

**Comment by carolyncaron** [comment]
Seeing as this issue is already several months old (and we haven't been poked by anyone), I don't think it is high priority, but it might be nice to revisit this when @Jiu9Shen has nothing on his plate.
Perhaps we want to get an update from Larissa regarding any updates that may have occurred to the VCF file. She may also be the one to ask regarding which species are wild.

**Comment by laceysanderson** [comment]
This is back to being a high priority now that we are readying the Wild germplasm for entry into KnowPulse.
